/* globe - display the currently-lighted face of the Earth in ASCII
**
** Copyright (C) 1994 by Jef Poskanzer <jef@mail.acme.com>.
** All rights reserved.
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions
** are met:
** 1. Redistributions of source code must retain the above copyright
**    notice, this list of conditions and the following disclaimer.
** 2. Redistributions in binary form must reproduce the above copyright
**    notice, this list of conditions and the following disclaimer in the
**    documentation and/or other materials provided with the distribution.
**
** THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
** ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
** ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
** FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
** DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
** OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
** HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
** LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
** OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
** SUCH DAMAGE.
*/

#include <stdio.h>
#include <time.h>
extern int atoi(char *nptr);
extern int abs(int);

static char *globes[30] = {
"             ._o##HMP'\"\"\"&&Z##o_\n"
"          _od'`\"\"' \"\"?\\ HMM9MMMMMHb_\n"
"       .dHM'        `9M#HMMMMMMMMMMMMb.\n"
"     .d#\"\"'         ooHM#9HMMMMMMMMMMMMb.\n"
"    d*'             HMMdbdd+'*HH#MMMMMMMM?\n"
"  ./'            ..?MMMMMMM#bd##obMMMMMMMMb\n"
"  H              $MMMMMMMMMMMMMMMMM&MMMRMHMH\n"
" d6.            |MMMMMMMMMMMMMMMMMMM&HMMM|`9b\n"
"|             - {MMMMMMMMMMMMMMMMMMMM&MH''  H|\n"
"MMH|            `9MMMMMMMMMMMMMMMMMMMMM#H'  `H\n"
"MMMM#.            \"**\"\"'\"#MMMMMMMMMMMMMM|    |\n"
"MMMMMb\\                   |MMMMMMMMMMMH'     |\n"
"MMMMMMMMHo                `?MMMMMMMMMM       |\n"
"MMMMMMMMMH                  MMMMMMMMMb  .    |\n"
"|*MMMMMMM.                 |MMMMMMMMM*,H|   .|\n"
" \\TMMMMMM'                 `MMMMMMMP',M?.   /\n"
" `|9MMMR'                   HMMMMMP' `'    |\n"
"  `?9MMM                    `MMMH'        /\n"
"    \\MMH                     \"\"         ,/\n"
"     `*M\\                             ./'\n"
"       `*\\o   ..                    ,+'\n"
"          \"-\\,_                 _.-\"\n"
"              \"^~-v_o#######d#\"\""
,
"              _o#>MMMM?\"\"`?&##o_.\n"
"          _dHH''+\"\"  \"\"-o.+MMMMMMHb_\n"
"       .dHMMM'         `9M#MMMMMMMMMMb.\n"
"     .dMH*\"\"\"          ,odMH*MMMMMMMMMMb.\n"
"    dMP'         --    `HMMdo&/*`#M#MMMMM?\n"
"  .dP'                .?MMMMMMM#o##boMMMMMb\n"
"  HM|                ?MMMMMMMMMMMMMMMMMMMMM&\n"
" d\"Mb_               MMMMMMMMMMMMMMMMMMMHMM|\\\n"
"|M    |              MMMMMMMMMMMMMMMMMMM6MH'`|\n"
"|MdMH#.              `HMMMMMMMMMMMMMMMMMMMH| |\n"
"|`MMMMH#\\              `**\"\"'`#MMMMMMMMMMMM' |\n"
"||MMMMMMMo_                    HMMMMMMMMMH'  |\n"
"||MMMMMMMMMMHb.                `HMMMMMMMM'   |\n"
"|`MMMMMMMMMMMH'                 |MMMMMMMM..  |\n"
"| `HMMMMMMMMM                  .MMMMMMMMH,& .|\n"
" \\  TMMMMMMMM                  `HMMMMMM',H: /\n"
" `| `HMMMMM\"'                   MMMMMH' \"' |\n"
"  `\\ /MMMMP                     |MMH\"'    /\n"
"    \\.`MMH'                     `\"'     ,/\n"
"     `\\:HM.                           ./'\n"
"       `~Z#\\v    .                  ,/'\n"
"          \"-\\_ \\.               _.-\"\n"
"              \"\"b~v\\_od#####=d\"\""
,
"              _odp$MMMHR:\"\"\"##o_\n"
"          _d$MMH\" \"*\"  \"\" \\\\+HHMMHb_\n"
"       .dHMMMHMR          \"*HHMMMMMMMb.\n"
"     .dMMMM*\"'\"'           vdMM#MMMMMMMb.\n"
"    dMMMP'            -    |HM6bdd#`HMHMM?\n"
"  .dMHP'                 ..|MMMMMMHbd#bMMMb\n"
" .H' &b                  :HMMMMMMMMMMMMMMMMH\n"
" d[p\"9H\\_.               |MMMMMMMMMMMMMMMMMMb\n"
"|`HH     '               |MMMMMMMMMMMMMMMMMMT|\n"
"| `boHMH#L               ``MMMMMMMMMMMMMMMMMH|\n"
"|   dMMMMMH#\\              ``#\"\"\"\"*HMMMMMMMMM|\n"
"|. |MMMMMMMMMo\\                    |MMMMMMMM||\n"
"|  |MMMMMMMMMMMMM#\\                `9MMMMMMH |\n"
"|   9MMMMMMMMMMMMM?                 |MMMMMM|.|\n"
"|    *HMMMMMMMMMM|                 .MMMMMMM\\L|\n"
" \\     HMMMMMMMMM'                 `MMMMMP\\P/\n"
" `\\    |MMMMMMP\"'                   MMMMP'^7\n"
"  `\\    9MMMMM'                    .MMH'  /\n"
"    \\.  `MMMH'                      \"   ,/\n"
"     `\\. `HM|                         ./'\n"
"       `~\\ *H\\,    ..               ,/'\n"
"          \"-\\_  ,\\              _.-\"\n"
"              \"-+#qo\\_ood###==\"\""
,
"             ._o##M'MMMMH?:'-qo_\n"
"          _dH*SMMM\" `\"\"  \"\" \\o&HMHb_\n"
"       .dHMMMMMMHML          \"*HMMMMMb.\n"
"     .dMMMMMMH*\"'\"'           ,dMM#MMMMb.\n"
"    dMMMMMM*'            --    *MMb&d?*MH?\n"
"   dMMM#M''                   .|MMMMMHb#bMb.\n"
"  HMH' .H\\                   `]MMMMMMMMMMMMH\n"
" /|MLd/'9Hb__                 MMMMMMMMMMMMMMb\n"
"|  `HM+      '                MMMMMMMMMMMMMMM|\n"
"|    |bodMM##?                `9MMMMMMMMMMMMMH\n"
"|      |MMMMMMH#b               \"**\"\"\"#MMMMMMM\n"
"|   . |MMMMMMMMMMbo_                   MMMMMMM\n"
"|     |MMMMMMMMMMMMMMMb,               `MMMMMM\n"
"|      ?MMMMMMMMMMMMMMH'                MMMMMH\n"
"|       ?HMMMMMMMMMMMM'                JMMMMM|\n"
" \\        |MMMMMMMMMMP                 MMMMRP\n"
" `|        MMMMMMMR\"\"                  MMMP7\n"
"  `\\       9MMMMMH'                   |MH'/\n"
"    \\.     |MMMH?                     `',/\n"
"     `\\.    TMM'                      ./'\n"
"       `~\\   `HL.-    .             ,/'\n"
"          \"-\\_  ' ,, .          _.-\"\n"
"              \"-~~HHo__,od##==^\"'"
,
"              _od#HM[\"MMMM:$--v_.\n"
"          ,oHMR'$HMM: `\"'  \"' -HHHb_\n"
"       .dHMMMMMMMMM#M?         `*&MMMb.\n"
"     .dMMMMMMMMMH\"\"'`\"           ,HMHMMb.\n"
"    /MMMMMMMMMP'             -    *H6ddPH?\n"
"   /JMMMMM#M''                    .MMMMM#Hb\n"
"  | MMM?   H&,                   `HMMMMMMMMH\n"
" /  |MM_#|`\"DHb\\_.                HMMMMMMMMMb\n"
"|    \"\"HM#.      !                |MMMMMMMMMM|\n"
"|       `HoodMMH##_               `*MMMMMMMMMH\n"
"|         `|MMMMMMMH#o              `**\"'*MMMM\n"
"|      .  |MMMMMMMMMMMbo.                 dMMM\n"
"|         &MMMMMMMMMMMMMMMMb.             |MMM\n"
"|          9MMMMMMMMMMMMMMMH'             |MMH\n"
"|           *HMMMMMMMMMMMMT               HMM|\n"
" \\            TMMMMMMMMMMM'              |MMP\n"
" `|           `MMMMMMMM'\"'               dMH\n"
"  `\\           MMMMMMH'                 ,MP\n"
"    \\.         MMMM#'                   i/\n"
"     `\\.       TMM?                   ./'\n"
"       `~\\     `*M?,-    _          ,/'\n"
"          \"-\\_    ` ,, .        _.-\"\n"
"              \"-\\=vHMb__ooo#==-\""
,
"              _od#HMM6&*MMMH::-_\n"
"          _dHMMMR\?\?MMM? \"\"| `\"'-?Hb_\n"
"       .~HMMMMMMMMHMMM#M?        `*HMb.\n"
"     ./?HMMMMMMMMMMM\"*\"\"\"           &MHb.\n"
"    /'|MMMMMMMMMMM'             -   `*MHM\\\n"
"   /  |MMMMMMHHM''                   .MMMHb\n"
"  |   9HMMP   .Hq,                   TMMMMMH\n"
" /     |MM\\,H-\"\"&&6\\__               `MMMMMMb\n"
"|       `\"\"HH#,       \\             - MMMMMMM|\n"
"|           `HoodHMM###.              `9MMMMMH\n"
"|              .MMMMMMMM##\\             `*\"?HM\n"
"|         ..  ,HMMMMMMMMMMMo\\.              |M\n"
"|             |MMMMMMMMMMMMMMMMHo           |M\n"
"|              ?MMMMMMMMMMMMMMMM*           |H\n"
"|.              `#MMMMMMMMMMMMM'           .M|\n"
" \\                `MMMMMMMMMMM*            |P\n"
" `\\                MMMMMMMMT\"'            ,H\n"
"  `\\              `MMMMMMH?              ./\n"
"    \\.            |MMMH#\"               ,/\n"
"     `\\.          |MMP'               ./'\n"
"       `~\\        `HM:.-    .       ,/'\n"
"          \"-\\_       '_\\ .      _.-\"\n"
"              \"-\\-#odMM\\_,oo==-\""
,
"              _od#HMMMMM&HMM#~o_.\n"
"          _vHMMMMMM$`9MMb_\"\"' \"'`\\b_\n"
"       .~'|MMMMMMMMMMMMMMHM\\.     `\"#b.\n"
"     ./' ,MMMMMMMMMMMMMP*\"'\"'        `Mb.\n"
"    /'  |MMMMMMMMMMMMM'             - `*M?\n"
"   /     MMMMMMMM#HM'                   9Mb\n"
"  |      99MMM'    9\\\\                 `TMMH\n"
" /         HMM\\,#|\"\"?pMb__.             |MMMb\n"
"|           \"\"\"#M#+       `|           - MMMM|\n"
"|                ?\\oodHMH##L.            `HMMH\n"
"|                  `|MMMMMMMM#b,          `*\"H\n"
"|              -   |MMMMMMMMMMMMo_           |\n"
"|                  &MMMMMMMMMMMMMMMHo        |\n"
"b                   9MMMMMMMMMMMMMMM*        |\n"
"|,                   *HMMMMMMMMMMMM?        .|\n"
" \\                     TMMMMMMMMMM?         /\n"
" `|  -                 dMMMMMMMP\"'         /'\n"
"  `\\                   MMMMMMH'           /'\n"
"    \\.                |MMMH#\"           ,/\n"
"     `\\.              MMH'            ./'\n"
"       `~\\            HM:..   .     ,/'\n"
"          \"-\\_          .\\      _.-\"\n"
"              \"-\\-odbo#ML_oo-=-\""
,
"             ._od#HMMMMHMR&M##-_\n"
"          _/dMMMMMMMM[:$MMb\\:\"|\"\"^~_\n"
"       .~'' |MMMMMMMMMMHMMMMH&\\    `\"\\.\n"
"     ./'   .HMMMMMMMMMMMMMMP*'\"'      \"\\.\n"
"    /'     |MMMMMMMMMMMMMM'             *?\n"
"   /        HMMMMMMMMHHM?                !b\n"
"  |         `6HMMM|    T|+.              `9H\n"
" /|          ` HMM?_dH`\"\"&$bo__           `Mb\n"
"|               ``\"*HH#|       \\           TM|\n"
"|                    `*bo\\#MMH##_          `HH\n"
"}                       ']MMMMMMMH#\\        `H\n"
"|                   .   dMMMMMMMMMMMo\\       |\n"
"|                       MMMMMMMMMMMMMMMH,    |\n"
"|                       `HMMMMMMMMMMMMMH'    |\n"
"|                        `*MMMMMMMMMMMM'    .|\n"
" \\                          MMMMMMMMMM'     /\n"
" `|                        |MMMMMMM?\"'     |\n"
"  `\\                       MMMMMMH'       /\n"
"    \\.                    HMMM#?'       ,/\n"
"     `\\.                 ?MM*'        ./'\n"
"       `~\\               MM?..  .   ,/'\n"
"          \"-\\_            _o.   _.-\"\n"
"              \"-\\-vod#od#M:o-~-\""
,
"             ._od#dHMMMMMMM9##o_\n"
"          _\\H#*MMMMMMMMM\?\?9Mbd$\"\"`._\n"
"       .~^\"   `HMMMMMMMMMMMMMMMHb.  `\\.\n"
"     ./'      ,HMMMMMMMMMMMMMMP\"'\"    `\\.\n"
"    /'        |MMMMMMMMMMMMMMT         -`\\\n"
"   /           `MMMMMMMMMHHH?             \\\n"
"  |.            `H*MMMP    !Pq\\           `\\\n"
" / `|              *MMH_,#|\"\"?&6o_.        `b\n"
"|                    \"\"\"#M##       \\        +|\n"
"|                         `#oooHMH##\\        \\\n"
"| .                          'MMMMMMMH#,     |\n"
"|                       ..   HMMMMMMMMM6\\.   |\n"
"P                           |MMMMMMMMMMMMMH, |\n"
"| .                          |MMMMMMMMMMMMH' |\n"
"|!                            `HMMMMMMMMMH  .|\n"
" \\   '                          MMMMMMMMH'  /\n"
" `|                            ,MMMMMMP\"   |\n"
"  `\\                          .MMMMMH'    /\n"
"    \\.                       ,HMM#*\"    ,/\n"
"     `\\.                    .MM*'     ./'\n"
"       `~\\                  MR\"-  _ ,/'\n"
"          \"-\\_              _o.._.-\"\n"
"              \"-\\-vooo#oo#HS-~-\""
,
"              _od#d&&MMMMMMM##o_.\n"
"          _~?MH**MMMMMMMMM$$*Mb&P+._\n"
"       .~^-\"'    \"MMMMMMMMMMMMMMMM\\_`\\.\n"
"     ./'          HMMMMMMMMMMMMMMR*\"  `\\.\n"
"    /'            9MMMMMMMMMMMMMM.      `\\\n"
"   /               `HMMMMMMMMH#M:         \\\n"
"  |  .              `*&MMMM    `Hq,        |\n"
" /    \\.              '`HMM?_dH`\"`H6o_.     \\\n"
"|                        ``\"\"HH#|     `|    `|\n"
"|                              ?\\ooHMH##.    |\n"
"|                                 |MMMMMM#,  |\n"
"|                            .   |MMMMMMMMb\\ |\n"
"|-'                              &MMMMMMMMMMH|\n"
"|   .                            `HMMMMMMMMMH|\n"
"|_`                               `HMMMMMMMM.|\n"
" \\                                  MMMMMMM'/\n"
" `|                                JMMMMM''|\n"
"  `\\                              ?MMMM*' /\n"
"    *b                           dMM#'' ,/\n"
"     `\\.                       .HH*'  ./'\n"
"       `~\\                    |MP: .,/'\n"
"          \"-\\_               .,:_.-\"\n"
"              \"-~-_oooodbod##:-\""
,
"              _od>d&&&HMMMMM##o_.\n"
"          _~/\"TMH**HMMMMMMMM$$&MHk~_\n"
"       .~''-`\"'    `*HMMMMMMMMMMMMMHZ>.\n"
"     ./'             |MMMMMMMMMMMMMMP'`\\.\n"
"    /'               `HMMMMMMMMMMMMM.   `\\\n"
"   /                   `HMMMMMMMMHH[      \\\n"
"  |                     `*RHMMM    `Db     |\n"
" /       `|                 *MMb_?#\"\"\\Mo_.  \\\n"
"|                             \"\"\"#M#|    `. `|\n"
"|                                  `\\odHM#b  |\n"
"|                                     TMMMMH||\n"
"|  -                              .  |MMMMMMMd\n"
"|   -                                {MMMMMMMM\n"
"H    -                               `MMMMMMMH\n"
"|. . '                                |MMMMMM|\n"
" \\\\`        '                          dMMMMP\n"
" `|                                   ?MMMH7\n"
"  `\\                                 ?MMM*/\n"
"    \\:\\,                           .dMH*\\/\n"
"     `\\H.-                        ,M*'./'\n"
"       `~\\                      .H*:,/'\n"
"          \"-\\_                 _\\,-\"\n"
"              \"-\\-\\,ooooo#oo=d\"\""
,
"              _o#>?&&&&HMMMM##o_\n"
"          _od*\"\"TMH*\"#MMMMMMMM$&HHb_\n"
"       .//\"'--`\"\"     `\"HMMMMMMMMMMMMb.\n"
"     ./'                 MMMMMMMMMMMMMT\\.\n"
"    /'                   `HMMMMMMMMMMM? `\\\n"
"   /                       `HMMMMMMMM#L   \\\n"
"  |                          `HHMMM   `H\\  |\n"
" /          ``|                 ?HMb_#|'9b\\.\\\n"
"|'                                ``\"#Hb   `:|\n"
"|                                      *bdMHL|\n"
"|                                        |MMMH\n"
"|     -                               .  MMMMM\n"
"H,      '                               |MMMMM\n"
"M`|     -                                MMMMH\n"
"|. ,  . `       .                        |MMM|\n"
" \\.., '                                  ,MMP\n"
" `&,                                    .HMH'\n"
"  `9,                                  ,MMP\n"
"    *, `\\,                            ?MH?\n"
"     `\\.|| -                        ,&&>'\n"
"       `~\\                        ,&6>'\n"
"          \"-\\_                 ._v~\"\n"
"              \"^~-v_,ooooodb~=\"\""
,
"              _od#d?&&&&&MMM##o_.\n"
"          _vH##\"\"\"?MM#\"*HMMMMMMMZ&b_\n"
"       .d/>'\"  - '\"'     `\"HMMMMMMMMMb.\n"
"     .d*'                   TMMMMMMMMMM+.\n"
"    d*'                      *MMMMMMMMMM/\\\n"
"   /'                          `HMMMMMMHb \\\n"
"  |                              `HMMM| `\\\\|\n"
" /               `~                 *MH\\#P*b\\\n"
"| '                                   \"\"*H| `|\n"
"|                                        `9oMH\n"
"|                                          `MM\n"
"L                                        - |MM\n"
"Mb?.       -'                              &MM\n"
"[P|\"\\       -   .                          |MH\n"
"|M,   .  _  `                              |M|\n"
" 9H\\  \\  \"                                 |P\n"
" `HMb                                     ,H\n"
"  `9Mb                                  .?P\n"
"    *H|   \\b                           .H?\n"
"     `<!  |R                         .d*'\n"
"       `~\\                         .d*'\n"
"          \"-\\_                  _,-\"\n"
"             `\"\"\\=v\\_,oooood~~-\"'"
,
"              _od#&&$?&&&&MM##o_.\n"
"          _odMM#\"\"'\"\"9MM*\"#MMMMMMHb\\\n"
"       .dH*:/'\"- -- \"\"      `*HMMMMMMb.\n"
"     ./M#^'                    ?MMMMMMMb.\n"
"    dMp'                        `HMMMMMMM?\n"
"  ./'\"                            `*MMMMMMb\n"
" ./-                                `HMMM `&\n"
" /                   `-|               ?Mb?Pb\n"
"|'  '                                    `\"&||\n"
"M                                           \\M\n"
"T                                            T\n"
"Mo.           -                            . M\n"
"T9Mb?\\.        -`                            M\n"
"P_?P? \"\\        -                            H\n"
"|MbH,    .   _  `                           ||\n"
" 9MMH\\   v.  '                              /\n"
" `HMMMH.                                   /'\n"
"  `9MMMH                                 ./'\n"
"    \\:*H|    `b,                        ,/\n"
"     `\\.`    dT                       ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"             `\"\"*bqb__,ooooo~=-\""
,
"              _od#M&&&?$&&HM##o_.\n"
"          _oHH#MM#\"\"'\"\"*MMP\"#HMMMHb_\n"
"       .dHMM? ~\"''  ---\"'     `\"#MMMMb.\n"
"     .dM#M#^'                    `*MMMMb.\n"
"    dMM?&'                         `HMMMM?\n"
"  .dP|'\"                             \"*MMMb.\n"
"  HT-                                  `HMb\\\n"
" /:                       `~             `HHb\n"
"|||                                        `*|\n"
"PH|                                          \\\n"
"M\"'`                                         |\n"
"M&\\o_ .                                      {\n"
"R+\"9HMbv+\\           `                       |\n"
"T*'_:9`b ``\\             .                   |\n"
"| dMbJH.     ,   ..  ^                      .|\n"
" \\MMMMMH\\    \\   `  .                       /\n"
" `HMMMMMMH.                                |\n"
"  `9MHHMMMH                               /\n"
"    *. `*#H     `&o                     ,/\n"
"     `\\.  `'    dP'                   ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"             `\"\"*#&#b__,oooo-~-\""
,
"              _od#HM6&&$?&&M##o_\n"
"          _oHMM##HMH*\"\"\"\"`HMM\"#HMHb_\n"
"       .dHMMMM* .*'` - - `\"'    `\"*MMb.\n"
"     .dMMM#&H*^'                    ?MMb.\n"
"    dMM&M:d/'                        `*MM?\n"
"  .dMM| '\"                             `*Mb.\n"
"  HMMT-                                  `HH\n"
" dH\":                         \"~.          ?b\n"
"|M ||     .                                 `|\n"
"M?.4[                                        |\n"
"M,H''                                        |\n"
"MMMp]ov_.               -                    |\n"
"H$\"b\":99MHo++\\           -                   |\n"
"|\"`\"*._:`T`=  \"b          -                  |\n"
"|   ?HMb_M?      .,   _  `-                 .|\n"
" \\ ,MMMMMMMb_    v.   '                     /\n"
" `|`MMMMMMMMMb                         -   |\n"
"  `\\`HMH#MMMMM                            /\n"
"    \\:'  `\"###      `#v                 ,/\n"
"     `\\.     \"     o&'                ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"             `\"\"*#HH##__,ooo-~-\""
,
"              _od#HHM6&&&?$&##o_\n"
"          _oHMMMMH##RM#\"\"\"\"`#MM\"#Hb_\n"
"       .dHMMMMMMH' .*\"` - - `'    `\"Hb.\n"
"     .dMMMMMH#$&+-\"                  `9b.\n"
"    dMMMM#][_d&'                       `H?\n"
"  .dMMMMH |'\"`                           `\\\n"
"  HMMMMM'-                                `\\.\n"
" /MMH\"::                          \"~.       \\\n"
"|?MM  Hi      `                             `|\n"
"|T?' ||M                                     |\n"
"|H|.d}`'  '                                  |\n"
"|9LMM&p!|o,_. .              -               |\n"
"|`H\?\?|\\`\":PHMHovd\\_            '             |\n"
"|  \"\"\"?* :_:`T`b. `?\\             .          |\n"
"|      ?#MML.M?       ,   ..  `             .|\n"
" \\   .dMMMMMMMM#.    .\\   `                 /\n"
" `|  `HMMMMMMMMMMb                         |\n"
"  `\\  `9MM##MMMMMM                        /\n"
"    \\.  \"   `\"##H|      :b,             ,/\n"
"     `\\.        `'    ,d*'            ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_ .                _.-\"\n"
"              \"\"*#HMM##:_,oo---\""
,
"             ._o##HM&M6&&&$?##o_.\n"
"          _oHMMMMMMH##H9M*\"'\"`#HMb\\_\n"
"       .dHMMMMMMMMMM  :\"'' - - \"   `\"\\.\n"
"     .dMMMMMMMMH#\"&b-\"                `\\.\n"
"    dMMMMMMM#TM_,#?                     `\\\n"
"  .dMMMMMMMM  \"''                         \\.\n"
" .HMMMMMMMM: -                      .      |\n"
" dHTMMMH\"':                          `^|    \\\n"
"|P `MMH  |6.                                `|\n"
"M'`|P#' ,|M6                                 |\n"
"T  &H .dM-\"'                                 |\n"
"|  9M.MMH#r?|ov\\_                -           |\n"
"|   `6:$'#|`\"\"?*MMHov*,.          -'         |\n"
"|     \"\"`*?\" __:\"9\"*=  \"\"|         -         |\n"
"|         .d#MM6_MH.       |   _  `-        .|\n"
" \\      .oHMMMMMMMMH\\     v.   '            /\n"
" `|     `MMMMMMMMMMMMH.                    |\n"
"  `\\     `MMM##HMMMMMM'                   /\n"
"    \\,    `'    \"\"###'      Tb          ,/\n"
"     `\\.           `\"     o/' -       ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"\"*#HMMMMHc_,o---\""
,
"              _o##HMM&MM&&&&:#o_\n"
"          _oHMMMMMMMMM###&MP\"'\"*#H+_\n"
"       .dHMMMMMMMMMMMMM  :*  - --'  `\\.\n"
"     .dMMMMMMMMMMMM#*\\H~'             `\\.\n"
"    dMMMMMMMMMMH?ML_oH'                 `\\\n"
"  .dMMMMMMMMMMM}  *\"'                     \\\n"
" .HMMMMMMMMMMMH: -                     .   |\n"
" /MMH\"MMMHM?\" :                         `~. \\\n"
"|'M'  9MMM|  -M,       `                    `|\n"
"|.M   |i**' .~TM.                            |\n"
"| \"  |&M  .dM| \"'  '                         |\n"
"|     9ML|MMH>p'*,o._.  .            -       |\n"
"|      `H\?\?\?'#\\ \"\"`P9MM#vv+\\.         -'     |\n"
"|        `\"\"`\"\"*'.__``&\"*~  \"b.       -  .   |\n"
"|             .d#HMM\\_Mb       .   _  `    ..|\n"
" \\          ,oHMMMMMMMMM#.    ..   '        /\n"
" `|         9MMMMMMMMMMMMM|                |\n"
"  `\\         9MMH##HMMMMMM'               /\n"
"    \\.        \"     `?#H#'     .H.      ,/\n"
"     `\\.               \"'    ,p''-    ./'\n"
"       `\\\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"             `\"\"*#HMMMMMM#:o---\""
,
"             ._od#HMMM6HM&&&#>o_\n"
"          _oHMMMMMMMMMMMH##*MM\"\"`b\\_\n"
"       .dHMMMMMMMMMMMMMMMH. ?'  - ^ `\\.\n"
"     .dMMMMMMMMMMMMMMMH#'db-'         `\\.\n"
"    dMMMMMMMMMMMMMMH`M\\_oM'             `\\\n"
"  .dMMMMMMMMMMMMMMM|  \"\"'                 \\\n"
"  H#MMMMMMMMMMMMMMHi -                   . |\n"
" d? MMM*\"HMMMPM?\"':.                      `\\\\\n"
"|'  MP' .`9MMM|   4b        '               `|\n"
"H   M|  ` d`**'  /'Hb                        |\n"
"|   `'   q/H  .,HD \"'                        |\n"
"|        `&ML:MMM$cr!P,ov_.              -   |\n"
"|          `H$:?'`*|`\":9\"HMMbv/\\\\         '  |\n"
"L            `\"\"\"\"\"?\" :__\"`T`b| `?|          /\n"
"|,                 _d#MM6_JH,      |  .. -  ,|\n"
" \\.             _odMMMMMMMMMH\\    ,.  `     /\n"
" `|             HMMMMMMMMMMMMM|            |\n"
"  `\\             MMMH##HMMMMMM'           /\n"
"    \\.  .        `\"     `*#H*'     M.   ,/\n"
"     `\\.                  `\"    ,~''  ./'\n"
"       `~:                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"^*#HMMMMMMM#&---\""
,
"             ._od#HMMMMMHM6&##o_\n"
"          _dHMMMMMMMMMMMMMMH##9R'^~_\n"
"       .dHMMMMMMMMMMMMMMMMMMH,`*   `\"\\.\n"
"     .dMMMMMMMMMMMMMMMMMMM#*iD~'      `\\.\n"
"    dMMMMMMMMMMMMMMMMMM#`M\\,dH          `\\\n"
"  .dMMMMMMMMMMMMMMMMMMMH  *\"'             \\\n"
"  HMH#MMMMMMMMMMMMMMMMHb -                 $\n"
" dMM' $MMMH'`HMMMM\\H\"' :                    \\\n"
"|M?'  `MM'  .`TMMMH   -M\\       `           `|\n"
"MM'    Mb   ` |i`#'  ./!ML                   |\n"
"M|      \"    ?bM|  .oHr``'  `                |\n"
"H             $MM_|MMM\\#/ |o\\\\_            - |\n"
"|              `*6\?\?:'|*|`\":9\"MMHov+\\       '|\n"
"H.                \"\"\"`\"'*' __.\"9\"*~ `\"|      ?\n"
"|H|                    .,##MML_Mb      | . `.|\n"
" 9b.                .,oHMMMMMMMMM?    \\  `  /\n"
" `&                 |MMMMMMMMMMMMM|        |\n"
"  `\\                 9MMH##HMMMMMH'       /\n"
"    \\.    .          `\"     `###'    ,| ,/\n"
"     `\\.                      \"'  ,/^'./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"\"\\dHMMMMMMMMM=:-\""
,
"              _od#HMMMMMMMMM##o_.\n"
"          _dHMMMMMMMMMMMMMMMMH##M}~_\n"
"       .dHMMMMMMMMMMMMMMMMMMMMMb`9' `\\.\n"
"     .dMMMMMMMMMMMMMMMMMMMMMMH#`H/    `\\.\n"
"    dMMMMMMMMMMMMMMMMMMMMMM?9H.,M,      `\\\n"
"  .dHMMMMMMMMMMMMMMMMMMMMMMH  *\"'         \\\n"
"  HMMMM##MMMMMMMMMMMMMMMMMMS. -            |.\n"
" dMMMM*' `MMMMH'\"HMMMMPH?\" :.               \\\n"
"|MMH*'    9MP\"   /'MMMM|   |b.      .       `|\n"
"MMMH`     `Hb      M`**'  ,~TM,              |\n"
"MMM|        \"     #/H,  _dM~``'  '           |\n"
"MM'               `&ML.4MMH\\#$|\\ov_.         4\n"
"MM                  `*6:\?\?'?* \"\":PHMHo/\\.    |\n"
"MM,.                  `\"\"\"`\"'*'.:_\"\?\?*| `|   |\n"
"|M|d|                       .d#HM6.Mb     ,..|\n"
" 9LT|.|                  _odMMMMMMMMM,   , `/\n"
" `H/\"                    MMMMMMMMMMMMM     |\n"
"  `\\.                    9MMH##HMMMMH'    /\n"
"    \\.       .           `'    `*##*   ?\\/\n"
"     `\\.                         \"' ,/?/'\n"
"       `~\\   `                      ,~'\n"
"          \"-\\_                  _.-\"\n"
"              \"\"*#&MMMMMMMMM#b-\""
,
"             ._o<>HMMMMMMMMM##o_.\n"
"          _oHMMMMMMMMMMMMMMMMMMM#&b_\n"
"       .dHMMMMMMMMMMMMMMMMMMMMMMMb?\\`\\.\n"
"     .dMMMMMMMMMMMMMMMMMMMMMMMMMM*Tp' `\\.\n"
"    /HMMMMMMMMMMMMMMMMMMMMMMMMM>&,,M,   `\\\n"
"  .dH#MMMMMMMMMMMMMMMMMMMMMMMMMH `?'      \\\n"
"  HMMMMM[MH##MMMMMMMMMMMMMMMMMM&,-'        |\n"
" dMMPMMMMH'  `MMMMH*\"?MMMMM\\H\"'`:           \\\n"
"|MMM6MH$'     TMM'   .`TMMMH,   M\\     `    `|\n"
"MMMMMHH`      `HH.   ` .L`#*'  /'ML          |\n"
"MMMMMM'         `'    -#dH   _dH \"'  '       |\n"
"MMMMP'                 `9ML.HMMP#p!|oo_      |\n"
"MMMM                     `#6:?`'*|`\":PHMbd\\. |\n"
"MMMM| .                    `\"\"\"\"\"*'.:_\"P`|`\\ |\n"
"|MMMH,M.                        .?#HM6,M   .\\|\n"
" 9MM|`M| -                   .odHMMMMMMM|  ,/\n"
" `HMM `'                     HMMMMMMMMMM|  |\n"
"  `9M,                       JMMH##MMMM*' /\n"
"    *.           .           \"'    *H#' ,?\n"
"     `\\.                           -'.o/'\n"
"       `~\\      '                   ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"^*#HHHMMMMMMM##-\""
,
"              _od:&HMMMMMMMM##o_\n"
"          _dHMMMMMMMMMMMMMMMMMMMMD\\_\n"
"       .dHMMMMMMMMMMMMMMMMMMMMMMMMM&&~.\n"
"     .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMH*H`\\.\n"
"    dH9HMMMMMMMMMMMMMMMMMMMMMMMMMM*&,J? `\\\n"
"  .dM#bbHMMMMMMMMMMMMMMMMMMMMMMMMMM|`?'   \\\n"
"  HMMMMMMMMH]M###MMMMMMMMMMMMMMMMMMb -     |\n"
" dMMMMMPMMMMM*'  `9MMMMH'\"9MMMMTM\"'`_       \\\n"
"|MMMMMMbMM*?'     `MMP'    'HMMMb   M,      `|\n"
"MMMMMMMMH#P`       `Mb    ' ||`#'  .^M,      |\n"
"MMMMMMMMMP           `'    |b]b  .dH-\"' `    |\n"
"MMMMMMMH'                   !MM_|MMH>p\"\\o\\   |\n"
"TMMMMMM                       *M\?\?\?'#|\":T9M+\\|\n"
"|TMMMMM|  .                     \"\"\"\"\"*'__\"?*`#\n"
"||MMMMMD.dH                         .d#MMJ| .|\n"
" \\9MMMM `MP ..                   .odHMMMMM| /\n"
" `|*MMM! `'                      MMMMMMMMM||\n"
"  `\\`MM|                         MMH#HMMM*/\n"
"    \\:'                          \"   `#*\\/\n"
"     `\\.                             -?/'\n"
"       `~\\         '                ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"-+#HMM#MMMMMM##\"\""
,
"             ._od#/$HMMMMMMM##o_\n"
"          _oHMMMMMMMMMMMMMMMMMMMMHb_\n"
"       .dHMMMMMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"     .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9+.\n"
"    dM&+9HHMMMMMMMMMMMMMMMMMMMMMMMMMM*b]/\\\n"
"  .dMMHd#o#MMMMHMMMMMMMMMMMMMMMMMMMMMH,?' \\\n"
" .HMMMMMMMPMMMMM]MH##MMMMMMMMMMMMMMMMMb,-  |\n"
" dMMMMMMMMM9MMMMMH'  `\"MMMMM*\"?MMMMPH\" :    \\\n"
"|MMMMMMMMMMbMM*\"\"      ?MMT'   `?MMM?  9\\   \"|\n"
"MMMMMMMMMMMMH#H`'       ?HL      6`#'  /9L   |\n"
"P\"HMMMMMMMMMMH'           \"     q/H  .dD'' ' |\n"
"| HMMMMMMMMH\"                   `9ML:MMR#?\\o.|\n"
"| `MMMMMMMM                       `H$\?\?`#`:MMH\n"
"|  TMMMMMMM,  .                     \"\"\"\"*'_:P#\n"
"|  |MMMMMMM|,dH                         ?#MHL|\n"
" \\  9MMMMMi |M| ..                   ,dHMMMMP\n"
" `|  9MMMM' `\"'                     |MMMMMMH\n"
"  `\\  `HMM'                         JMH#MMP\n"
"    \\_ `\"               .           \"  |H?\n"
"     `\\.                              ./'\n"
"       `~\\            '             ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"-==&MMMM#MMMM##\"\""
,
"             ._-c>&R?$MMMMMM##o_\n"
"          _o$MHMMMMMMMMMMMMMMMMMMHb_\n"
"       .~1MMMMMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"     .<bdMM9MMMMMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"    /\\M6b>^9R#MMMMMMMMMMMMMMMMMMMMMMMMMDM?\n"
"   /dMMMMb##b#dMMMMHMMMMMMMMMMMMMMMMMMMMb*\\\n"
"  bMMMMMMMMMMM&MMMMM$MM##HMMMMMMMMMMMMMMM\\-\\\n"
" dMMMMMMMMMMMMM*MMMMMM*   `9MMMM#\"?MMMMH\"`. \\\n"
"|HMMMMMMMMMMMMMbMMH\"?       9MM'   \?\?MMH  \\.`|\n"
"|MMMMMMMMMMMMMMMH##|`       `HH,   ' b`*' /M |\n"
"|*\"'#MMMMMMMMMMMMM*           `'    ?/H  ?D` |\n"
"|    MMMMMMMMMMM?'                   *M?4MM#bd\n"
"|    ?MMMMMMMMM'                      ?M\?\?\?|:M\n"
"|     9MMMMMMMM|  .                     \"\"\"*_H\n"
"|     &MMMMMMMM}.oH|                      ,#M|\n"
" \\    `HMMMMMM: iMM  ..                 ,dMMP\n"
" `|    `HMMMMM' `\"'                    |MMMH\n"
"  `\\     *MMM|                        .MHHP\n"
"    \\.    `\"                          `',?\n"
"     `\\.                              ./'\n"
"       `~\\               `          ,/'\n"
"          \"-\\_                  _.-\"\n"
"              \"-~=q#HMMMHHMM##\"\""
,
"              _v~:S&M$?HMHMM##o_\n"
"          _.:$\\#MMMMMMMMMMMMMMMMMHb_\n"
"       .~'.HMHMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"     ./',odHMMMMMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"    /\" |M6&d\\\"?M&#MMMMMMMMMMMMMMMMMMMMMMM?\n"
"   / _HMMMMMbd##obHMMMMMMMMMMMMMMMMMMMMMMM}\n"
"  | dMMMMMMMMMMMMMPMMMMH[9M###MMMMMMMMMMMMMH\n"
" / dMMMMMMMMMMMMMMM/HMMMMMH'  `\"MMMM*\"HMMMT:\\\n"
"| |MMMMMMMMMMMMMMMMMdMM#\":      ?MM'  .\"MMb`6|\n"
"| |MMMMMMMMMMMMMMMMMMH#H|'       ?H\\  ` |?* &H\n"
"|  ?*\"\"*HMMMMMMMMMMMMMH'           \"    bH .H9\n"
"|       {MMMMMMMMMMMH'                  `MLMMM\n"
"|       `9MMMMMMMMMR                     `6?*H\n"
"L        `MMMMMMMMMH.  .                  `\"\"&\n"
"|.       |MMMMMMMMMM|,dM                    ?|\n"
" \\        *MMMMMMMT  dM| ..               ,dP\n"
" `|        TMMMMMM'  `\"                  ,MH\n"
"  `\\        `MMMH'                      .HP\n"
"    \\.       `\"                         i/\n"
"     `\\.                              ./'\n"
"       `~\\                          ,/'\n"
"          \"-\\_                . _.-\"\n"
"              \"-~=q###MMMMHM##\"\"'"
,
"              _o~~^?&M&?]MHM##o_\n"
"          _~^\"$?.#MMMMMMMMMMMMMMMHb_\n"
"       .~'  :MM#MMMMMMMMMMMMMMMMMMMMMb.\n"
"     ./'  .ooMHHMMMMMMMMMMMMMMMMMMMMMMMb.\n"
"    /'-   MM6bd>/\"#&#HMMMMMMMMMMMMMMMMMMM?\n"
"   /    ?MMMMMMHbd##o#HMMMMHMMMMMMMMMMMMMMb\n"
"  |   ?MMMMMMMMMMMMMMM69MMMM69MH##MMMMMMMMMH.\n"
" /   |MMMMMMMMMMMMMMMMML*MMMMMM?  `\"MMMH`HMM\\\n"
"|    HMMMMMMMMMMMMMMMMMMHHMH*''     ?MM' !9M||\n"
"|    9MMMMMMMMMMMMMMMMMMMM##H`'      ?M, ` R?\\\n"
"|     `*\"\"\"#MMMMMMMMMMMMMMMH'         `'  |d|d\n"
"|           |MMMMMMMMMMMMH'                9LM\n"
"M,          `9MMMMMMMMMMT                  `M]\n"
"M|            MMMMMMMMMMb   .               `*\n"
"|b           |MMMMMMMMMMH oH|               .|\n"
" 9,           *MMMMMMMM' ,MH  -            ./\n"
" `|            9MMMMMM\"  `\"'              .&\n"
"  `\\            ?MMMH'                   ./\n"
"    \\.           \"'                     ,/\n"
"     `\\.                              ./'\n"
"       `~\\.                    '    ,/'\n"
"          \"\\\\_                 ._.-\"\n"
"              \"-\\~q###HHMMMMd#\"\"'"
,
"              _odp^'\"?M&&?MH##o_\n"
"          _~^''`$+ #MM9MMMMMMMMMMHb_\n"
"       ./'     9MHHMMMMMMMMMMMMMMMMMMb.\n"
"     ./\"     ,ooM#MHMHMMMMMMMMMMMMMMMMMb.\n"
"    /'  --   MMM&o&~*`#&#HMMMMMMMMMMMMMMM?\n"
"   /     . ,HMMMMMM#bd##o#dMMMMHMMMMMMMMMMb\n"
"  |      ?MMMMMMMMMMMMMMMMMHMMMMM9MH#HMMMMMH\n"
" /      |MMMMMMMMMMMMMMMMMMM/HMMMMM|  \"HMM?Hb\n"
"|'      dMMMMMMMMMMMMMMMMMMMM&MM#\":    `MR !H|\n"
"T       `MMMMMMMMMMMMMMMMMMMMMH#H|'     `M,`|H\n"
"H        `**\"\"\"?HMMMMMMMMMMMMMMM*        `' |M\n"
"M\\               MMMMMMMMMMMMM*'             M\n"
"MMH,             `MMMMMMMMMMM!               T\n"
"MMM|              |MMMMMMMMMM|  .            |\n"
"|MM|              HMMMMMMMMMM|,dM           .|\n"
" 9ML              `MMMMMMMMT  dM' .         /\n"
" `H|               |MMMMMMP'  \"'           |\n"
"  `9,               ?MMMH'                /\n"
"    \\,               \"'                 ,/\n"
"     `\\.                              ./'\n"
"       `~\\ .                     `  ,/'\n"
"          \"-\\_                  _.-\"\n"
"             `\"-~-?######HMM##\"\"'"
,
"             ._o##H\"?\"\"S&&?9##o_\n"
"          _/^*'\" \":d.|MMPMMMMMMMMHb_\n"
"       .d/'      -9MHHMMMMMMMMMMMMMMMb.\n"
"     .~'\"       ,ooMHHHMMMMMMMMMMMMMMMMb.\n"
"    /'     -    |MMbbdb~'`&M#HMMMMMMMMMMM?\n"
"   /         ..?MMMMMMM#bd##b#dMMMMHMMMMMMb\n"
" .|         .]MMMMMMMMMMMMMMMMMMMMMMRMH#MMMH\n"
" d          |MMMMMMMMMMMMMMMMMMM&HMMMMH `*MM\\\n"
"|?          HMMMMMMMMMMMMMMMMMMMMbMM#':   TM`|\n"
"M|          `MMMMMMMMMMMMMMMMMMMMMM#H|     9,\\\n"
"MM|          `\"#\"\"\"\"*HMMMMMMMMMMMMMMP       '|\n"
"MMM\\                 |MMMMMMMMMMMMH'         |\n"
"MMMMMb,               `MMMMMMMMMMR           |\n"
"MMMMMM'                9MMMMMMMMMM  .        |\n"
"|MMMMM                ,MMMMMMMMMMH.dM       .|\n"
" 9MMMM                `9MMMMMMMR' dM'..     /\n"
" `HMM:                 `MMMMMMP'  \"'       |\n"
"  `9ML                  `MMMH'            /\n"
"    *M.                  \"'             ,/\n"
"     `\\\\                              ./'\n"
"       `\\v. .                      `,/'\n"
"          \"-v_                  _.-\"\n"
"              \"-~-\\o#######M##\"\"'"
};


extern time_t date_parse(char *str);

int main(int argc, char **argv)
{
  setvbuf(stdout, 0, _IOFBF, 0);
  time_t now = (argc > 1) ? date_parse(argv[1]) : time(0);
#define OFFSET 43200
  int indx = (now + OFFSET) % 86400 / (86400 / 30);
  puts(globes[abs(indx)]);
}
